### ISSUE TITLE
Title of a post in the post view is cropped

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#4] opened 2023-10-27 13:16 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. revive a notification in the inbox
2. Open the related post by clicking on the notification 
3. The title is “cropped” (not displayed properly)

https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/d67348fd-38c8-4079-b248-d8bf01f13aee

### Expected Behavior

Display the whole title properly.

### Version

0.2.5

### iOS Version

16.x

### Device

iPhone 12 Pro Max

**Comment by CreatureSurvive** [comment] 2023-11-04 16:22
I can't seem to reproduce this issue on my end, nonetheless, I believe I found the cause and have it resolved in the upcoming release.

**Closed as completed** 2023-11-05 03:31 UTC
Labels: bug

**Comment by Genfood** [comment] 2023-11-05 09:40
Seems to be fixed.
